const IMG_CARDS_URL =
  "https://b.zmtcdn.com/data/pictures/chains/6/18347416/c9fbbf2eed4d4ab83ce63b114e76b57f.jpg";

// config driven UI
export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

  export const ITEM_IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/";


export const IMG_URL = 'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/';

// stream of data for menu card
const restaurantListConfig = [
  {
    statusCode: 0,
    data: {
      cacheExpiryTime: 320,
      pages: 1,
      pageIndex: 0,
      scrubber: 0,
      filters: [],
      sorts: [],
      configs: {},
      cards: [
        {
          cardType: "seeAllRestaurants",
          layoutAlignmentType: "VERTICAL",
          data: {
            type: "seeAllRestaurants",
            data: {
              title: "SEE ALL",
              totalOpenRestaurants: 1858,
              cards: [
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "121603",
                    name: "Kannur Food Point",
                    uuid: "51983905-e698-4e31-b0d7-e376eca56320",
                    city: "1",
                    area: "Tavarekere",
                    totalRatingsString: "5000+ ratings",
                    cloudinaryImageId: "bmwn4n4bn6n1tcpc8x2h",
                    cuisines: ["Kerala", "Chinese"],
                    tags: [],
                    costForTwo: 30000,
                    costForTwoString: "₹300 FOR TWO",
                    deliveryTime: 27,
                    minDeliveryTime: 27,
                    maxDeliveryTime: 27,
                    slaString: "27 MINS",
                    lastMileTravel: 3,
                    slugs: {
                      restaurant: "kannur-food-point-btm",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "6/21,9TH CROSS ,1ST MAIN, VENKATESHWARA LAYOUT,SG PALYA, BENGALURU, - 560093",
                    locality: "SG Palya",
                    parentId: 20974,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "50% off",
                      shortDescriptionList: [
                        {
                          meta: "50% off on all orders",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off on all orders",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "50% OFF",
                      shortDescriptionList: [
                        {
                          meta: "",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off on all orders",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    ribbon: [
                      {
                        type: "PROMOTED",
                      },
                    ],
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 4100,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 4100,
                      message: "",
                      title: "Delivery Charge",
                      amount: "4100",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID:
                      "cid=5777394~p=1~eid=00000185-f8a4-4da5-1cab-9a8300c10122",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "3 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "121603",
                      deliveryTime: 27,
                      minDeliveryTime: 27,
                      maxDeliveryTime: 27,
                      lastMileTravel: 3,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: true,
                    avgRating: "3.9",
                    totalRatings: 5000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "229",
                    name: "Meghana Foods",
                    uuid: "4fdd19e2-5d0f-4bde-9c7f-dc3e8d36021f",
                    city: "1",
                    area: "Koramangala",
                    totalRatingsString: "5000+ ratings",
                    cloudinaryImageId: "xqwpuhgnsaf18te7zvtv",
                    cuisines: [
                      "Biryani",
                      "Andhra",
                      "South Indian",
                      "North Indian",
                      "Chinese",
                      "Seafood",
                    ],
                    tags: [],
                    costForTwo: 50000,
                    costForTwoString: "₹500 FOR TWO",
                    deliveryTime: 18,
                    minDeliveryTime: 18,
                    maxDeliveryTime: 18,
                    slaString: "18 MINS",
                    lastMileTravel: 1.2999999523162842,
                    slugs: {
                      restaurant: "meghana-foods-5th-block-koramangala",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "124, Near Jyothi Nivas College, 1st Cross, KHB Colony, Koramangala 5th Block, Bangalore",
                    locality: "5th Block",
                    parentId: 635,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID: "",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "1.2 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "229",
                      deliveryTime: 18,
                      minDeliveryTime: 18,
                      maxDeliveryTime: 18,
                      lastMileTravel: 1.2999999523162842,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: false,
                    avgRating: "4.4",
                    totalRatings: 5000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "425",
                    name: "Hotel Empire",
                    uuid: "cf522c0c-38fc-47c6-bb3a-071d40dd22e3",
                    city: "1",
                    area: "Koramangala",
                    totalRatingsString: "1000+ ratings",
                    cloudinaryImageId: "un4omn7rcunkmlw6vikr",
                    cuisines: ["North Indian", "Kebabs", "Biryani"],
                    tags: [],
                    costForTwo: 45000,
                    costForTwoString: "₹450 FOR TWO",
                    deliveryTime: 27,
                    minDeliveryTime: 27,
                    maxDeliveryTime: 27,
                    slaString: "27 MINS",
                    lastMileTravel: 1.2999999523162842,
                    slugs: {
                      restaurant: "hotel-empire-5th-block-koramangala",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "103, Industrial Area, 5th Block, Near Jyothi Nivas College, Koramangala 5th Block, Bangalore",
                    locality: "Koramangala",
                    parentId: 475,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "10% off",
                      shortDescriptionList: [
                        {
                          meta: "10% off | Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "10% off up to ₹40 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "10% OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "10% off up to ₹40 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID: "",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "1.2 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "425",
                      deliveryTime: 27,
                      minDeliveryTime: 27,
                      maxDeliveryTime: 27,
                      lastMileTravel: 1.2999999523162842,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: false,
                    avgRating: "4.1",
                    totalRatings: 1000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "5934",
                    name: "Burger King",
                    uuid: "ac56f2ac-71d3-4978-9513-b3aa68e25463",
                    city: "1",
                    area: "Koramangala",
                    totalRatingsString: "1000+ ratings",
                    cloudinaryImageId: "jpohkfkofao0hxez7vdh",
                    cuisines: ["Burgers", "American"],
                    tags: [],
                    costForTwo: 35000,
                    costForTwoString: "₹350 FOR TWO",
                    deliveryTime: 23,
                    minDeliveryTime: 23,
                    maxDeliveryTime: 23,
                    slaString: "23 MINS",
                    lastMileTravel: 1.399999976158142,
                    slugs: {
                      restaurant: "burger-king-koramangala",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "Unit No. 1, Davar Atrium, Corporation No. 118, Koramangala Industrial Area 7th Block, Bangalore 560095",
                    locality: "7th Block",
                    parentId: 166,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "60% off",
                      shortDescriptionList: [
                        {
                          meta: "60% off | Use STEALDEAL",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "60% off up to ₹120 | Use code STEALDEAL",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "60% OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use STEALDEAL",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "60% off up to ₹120 | Use code STEALDEAL",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    ribbon: [
                      {
                        type: "PROMOTED",
                      },
                    ],
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID:
                      "cid=5790199~p=4~eid=00000185-f8a4-4da5-1cab-9a8400c1042b",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "1.3 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "5934",
                      deliveryTime: 23,
                      minDeliveryTime: 23,
                      maxDeliveryTime: 23,
                      lastMileTravel: 1.399999976158142,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: true,
                    avgRating: "4.2",
                    totalRatings: 1000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "492159",
                    name: "Roti Wala",
                    uuid: "ada41f9b-cca3-4197-805c-8c43798919e9",
                    city: "1",
                    area: "Koramangala",
                    totalRatingsString: "100+ ratings",
                    cloudinaryImageId: "51f52730c0a08dc89dca3df021370477",
                    cuisines: ["Home Food", "North Indian", "Thalis"],
                    tags: [],
                    costForTwo: 20000,
                    costForTwoString: "₹200 FOR TWO",
                    deliveryTime: 28,
                    minDeliveryTime: 28,
                    maxDeliveryTime: 28,
                    slaString: "28 MINS",
                    lastMileTravel: 1,
                    slugs: {
                      restaurant: "new-roti-wala-koramangala-koramangala",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "No 18 ,MIG, KHB Colony, 5th Block, Koramangala, Bengaluru, Karnataka 560095, India",
                    locality: "5th Block",
                    parentId: 171678,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "20% off",
                      shortDescriptionList: [
                        {
                          meta: "20% off | Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "20% off up to ₹50 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "20% OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "20% off up to ₹50 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID: "",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "1 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "492159",
                      deliveryTime: 28,
                      minDeliveryTime: 28,
                      maxDeliveryTime: 28,
                      lastMileTravel: 1,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: false,
                    avgRating: "4.3",
                    totalRatings: 100,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "337335",
                    name: "Kannur food kitchen",
                    uuid: "c70b61bc-0f68-4e24-996b-749fbf295c35",
                    city: "1",
                    area: "BTM Layout",
                    totalRatingsString: "1000+ ratings",
                    cloudinaryImageId: "a27weqanhnszqiuzsoik",
                    cuisines: ["Kerala", "Biryani", "Beverages"],
                    tags: [],
                    costForTwo: 20000,
                    costForTwoString: "₹200 FOR TWO",
                    deliveryTime: 25,
                    minDeliveryTime: 25,
                    maxDeliveryTime: 25,
                    slaString: "25 MINS",
                    lastMileTravel: 2.5,
                    slugs: {
                      restaurant: "kannur-food-kitchen-btm-btm",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "kannur food point, Chocolate Factory Road, Tavarekere, Cashier Layout, 1st Stage, BTM Layout, thavrakharea, Karnataka, India",
                    locality: "1st  Stage",
                    parentId: 114756,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "50% off",
                      shortDescriptionList: [
                        {
                          meta: "50% off on all orders",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off on all orders",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "50% OFF",
                      shortDescriptionList: [
                        {
                          meta: "",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off on all orders",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID: "",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "2.5 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "337335",
                      deliveryTime: 25,
                      minDeliveryTime: 25,
                      maxDeliveryTime: 25,
                      lastMileTravel: 2.5,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: false,
                    avgRating: "3.8",
                    totalRatings: 1000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "65797",
                    name: "Leon's - Burgers & Wings (Leon Grill)",
                    uuid: "b5747bab-748b-4f2d-8856-25cd9a49efb3",
                    city: "1",
                    area: "Koramangala",
                    totalRatingsString: "1000+ ratings",
                    cloudinaryImageId: "r4ufflqojich0r29efvc",
                    cuisines: [
                      "American",
                      "Snacks",
                      "Turkish",
                      "Portuguese",
                      "Continental",
                    ],
                    tags: [],
                    costForTwo: 30000,
                    costForTwoString: "₹300 FOR TWO",
                    deliveryTime: 25,
                    minDeliveryTime: 25,
                    maxDeliveryTime: 25,
                    slaString: "25 MINS",
                    lastMileTravel: 1.2999999523162842,
                    slugs: {
                      restaurant: "leon-grill-koramangala-koramangala",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "Plot No.123 K.H.B Colony, 5th Block , Koramangala , Bangalore -95",
                    locality: "KHB Colony",
                    parentId: 371281,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "50% off",
                      shortDescriptionList: [
                        {
                          meta: "50% off | Use SPECIALS",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off up to ₹100 on select items | Use code SPECIALS",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "50% OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use SPECIALS",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off up to ₹100 on select items | Use code SPECIALS",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    ribbon: [
                      {
                        type: "PROMOTED",
                      },
                    ],
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID:
                      "cid=5791634~p=7~eid=00000185-f8a4-4da5-1cab-9a8500c10728",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "1.2 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "65797",
                      deliveryTime: 25,
                      minDeliveryTime: 25,
                      maxDeliveryTime: 25,
                      lastMileTravel: 1.2999999523162842,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: true,
                    avgRating: "4.3",
                    totalRatings: 1000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "428",
                    name: "Biryani Pot",
                    uuid: "6db20a8b-dd85-4148-b750-107169f7f826",
                    city: "1",
                    area: "Btm Layout",
                    totalRatingsString: "1000+ ratings",
                    cloudinaryImageId: "mdipoyzfzsa7n7igskht",
                    cuisines: ["North Indian", "Biryani"],
                    tags: [],
                    costForTwo: 50000,
                    costForTwoString: "₹500 FOR TWO",
                    deliveryTime: 20,
                    minDeliveryTime: 20,
                    maxDeliveryTime: 20,
                    slaString: "20 MINS",
                    lastMileTravel: 1.899999976158142,
                    slugs: {
                      restaurant: "biryani-pot-madiwala-junction-btm",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "14th  Cross, 4th link Road Maruthi Nagar Madiwala Bangalore 68",
                    locality: "Maruti Nagar",
                    parentId: 21798,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "20% off",
                      shortDescriptionList: [
                        {
                          meta: "20% off | Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "20% off up to ₹50 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "20% OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "20% off up to ₹50 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID: "",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "1.8 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "428",
                      deliveryTime: 20,
                      minDeliveryTime: 20,
                      maxDeliveryTime: 20,
                      lastMileTravel: 1.899999976158142,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: false,
                    avgRating: "3.8",
                    totalRatings: 1000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "342032",
                    name: "Bhartiya Jalpan",
                    uuid: "9bd9aa90-0b97-4f24-969a-3f16c5aafc66",
                    city: "1",
                    area: "HSR Layout",
                    totalRatingsString: "1000+ ratings",
                    cloudinaryImageId: "ybfyjdu8fhlgqj6i9dlh",
                    cuisines: ["North Indian", "Sweets", "Desserts", "Chaat"],
                    tags: [],
                    costForTwo: 45000,
                    costForTwoString: "₹450 FOR TWO",
                    deliveryTime: 31,
                    minDeliveryTime: 31,
                    maxDeliveryTime: 31,
                    slaString: "31 MINS",
                    lastMileTravel: 4.900000095367432,
                    slugs: {
                      restaurant: "bhartiya-jalpan-hsr-hsr",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "NO.2631,27TH MAIN ROAD, 1ST SECTOR , HSR LAYOUT, BANGALORE - 560102",
                    locality: "1st Sector",
                    parentId: 7518,
                    unserviceable: false,
                    veg: true,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    ribbon: [
                      {
                        type: "PROMOTED",
                      },
                    ],
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 4100,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 4100,
                      message: "",
                      title: "Delivery Charge",
                      amount: "4100",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID:
                      "cid=5717568~p=10~eid=00000185-f8a4-4da5-1cab-9a8600c10a18",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "4.9 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "342032",
                      deliveryTime: 31,
                      minDeliveryTime: 31,
                      maxDeliveryTime: 31,
                      lastMileTravel: 4.900000095367432,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: true,
                    avgRating: "4.1",
                    totalRatings: 1000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "10576",
                    name: "Pizza Hut",
                    uuid: "0e708f2b-f624-4324-a71c-f4a366902e1c",
                    city: "1",
                    area: "Koramangala",
                    totalRatingsString: "500+ ratings",
                    cloudinaryImageId: "oi37dtpuyb41nv7zlha7",
                    cuisines: ["Pizzas"],
                    tags: [],
                    costForTwo: 35000,
                    costForTwoString: "₹350 FOR TWO",
                    deliveryTime: 24,
                    minDeliveryTime: 24,
                    maxDeliveryTime: 24,
                    slaString: "24 MINS",
                    lastMileTravel: 0.699999988079071,
                    slugs: {
                      restaurant: "pizza-hut-6th-block-koramangala",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "#478, 80Ft Road, 17th F main, 6th Block, Koramangala Opp Vasan eye Care, Bangalore",
                    locality: "6th Block",
                    parentId: 721,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "50% off",
                      shortDescriptionList: [
                        {
                          meta: "50% off | Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off up to ₹100 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "50% OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off up to ₹100 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID: "",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "0.6 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "10576",
                      deliveryTime: 24,
                      minDeliveryTime: 24,
                      maxDeliveryTime: 24,
                      lastMileTravel: 0.699999988079071,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: false,
                    avgRating: "3.7",
                    totalRatings: 500,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "201224",
                    name: "Asha tiffins",
                    uuid: "e32381cf-6468-4c10-9bad-47fa08e898a8",
                    city: "1",
                    area: "HSR Layout",
                    totalRatingsString: "1000+ ratings",
                    cloudinaryImageId: "n15vckntsiboiod3gpco",
                    cuisines: ["Indian", "South Indian", "Beverages"],
                    tags: [],
                    costForTwo: 20000,
                    costForTwoString: "₹200 FOR TWO",
                    deliveryTime: 31,
                    minDeliveryTime: 31,
                    maxDeliveryTime: 31,
                    slaString: "31 MINS",
                    lastMileTravel: 4,
                    slugs: {
                      restaurant: "asha-tiffins-hsr-hsr-2",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "Asha Tiffins, 5th Main Road, Sector 7, HSR Layout, Bengaluru, Karnataka, India",
                    locality: "7th Sector",
                    parentId: 236243,
                    unserviceable: false,
                    veg: true,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "30% off",
                      shortDescriptionList: [
                        {
                          meta: "30% off | Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "30% off up to ₹75 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "30% OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "30% off up to ₹75 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 4100,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 4100,
                      message: "",
                      title: "Delivery Charge",
                      amount: "4100",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID: "",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "4 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "201224",
                      deliveryTime: 31,
                      minDeliveryTime: 31,
                      maxDeliveryTime: 31,
                      lastMileTravel: 4,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: false,
                    avgRating: "4.4",
                    totalRatings: 1000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "601",
                    name: "Litti Twist",
                    uuid: "e7dcc8d7-fea9-4312-8c4e-7a6516a026db",
                    city: "1",
                    area: "Btm Layout",
                    totalRatingsString: "500+ ratings",
                    cloudinaryImageId: "zyahkuhlgnxp3prkvttv",
                    cuisines: ["North Indian"],
                    tags: [],
                    costForTwo: 25000,
                    costForTwoString: "₹250 FOR TWO",
                    deliveryTime: 31,
                    minDeliveryTime: 31,
                    maxDeliveryTime: 31,
                    slaString: "31 MINS",
                    lastMileTravel: 4.5,
                    slugs: {
                      restaurant: "litti-twist-2nd-stage-btm",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "#5, 6th cross, 1st Main, Bannerghatta Main Rd, NS Palya, Stage 2, Bengaluru, Karnataka 560076",
                    locality: "2nd Stage",
                    parentId: 3455,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "50% off",
                      shortDescriptionList: [
                        {
                          meta: "50% off | Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off up to ₹100 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "50% OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "50% off up to ₹100 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    ribbon: [
                      {
                        type: "PROMOTED",
                      },
                    ],
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 4100,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 4100,
                      message: "",
                      title: "Delivery Charge",
                      amount: "4100",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID:
                      "cid=5693609~p=13~eid=00000185-f8a4-4da5-1cab-9a8700c10d62",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "4.5 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "601",
                      deliveryTime: 31,
                      minDeliveryTime: 31,
                      maxDeliveryTime: 31,
                      lastMileTravel: 4.5,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: true,
                    avgRating: "4.2",
                    totalRatings: 500,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "63957",
                    name: "Madeena Hotel",
                    uuid: "da15d34a-cf0f-40a6-8600-096309bb578b",
                    city: "1",
                    area: "Koramangala",
                    totalRatingsString: "1000+ ratings",
                    cloudinaryImageId: "yc0asfa2j9elggstyjg4",
                    cuisines: ["Biryani", "Mughlai", "Indian", "Beverages"],
                    tags: [],
                    costForTwo: 25000,
                    costForTwoString: "₹250 FOR TWO",
                    deliveryTime: 23,
                    minDeliveryTime: 23,
                    maxDeliveryTime: 23,
                    slaString: "23 MINS",
                    lastMileTravel: 1.399999976158142,
                    slugs: {
                      restaurant: "madeena-hotel-koramangala-koramangala",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "# 20/A, 5th Block Kormangala ,Next To Masjid-E-Mamoor Banglore-95",
                    locality: "5th Block",
                    parentId: 12517,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "15% off",
                      shortDescriptionList: [
                        {
                          meta: "15% off | Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "15% off up to ₹45 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "15% OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "15% off up to ₹45 | Use code TRYNEW",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID: "",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "1.3 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "63957",
                      deliveryTime: 23,
                      minDeliveryTime: 23,
                      maxDeliveryTime: 23,
                      lastMileTravel: 1.399999976158142,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: false,
                    avgRating: "4.1",
                    totalRatings: 1000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "410683",
                    name: "Soul Rasa",
                    uuid: "5fddc67b-5287-45a0-a252-c34eb9b290d1",
                    city: "1",
                    area: "Koramangala",
                    totalRatingsString: "1000+ ratings",
                    cloudinaryImageId: "xoth5ysuv2r6ctizaso5",
                    cuisines: [
                      "Indian",
                      "Healthy Food",
                      "Home Food",
                      "South Indian",
                      "North Indian",
                    ],
                    tags: [],
                    costForTwo: 40000,
                    costForTwoString: "₹400 FOR TWO",
                    deliveryTime: 26,
                    minDeliveryTime: 26,
                    maxDeliveryTime: 26,
                    slaString: "26 MINS",
                    lastMileTravel: 2.0999999046325684,
                    slugs: {
                      restaurant: "hb-koramangala-koramangala",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "88/1,Ward No.66, Sajjapura Road, Madiwala, Jakkasandra Village Bangalore-South, 560034",
                    locality: "Jakkasandra",
                    parentId: 239281,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "Flat ₹125 off",
                      shortDescriptionList: [
                        {
                          meta: "Flat ₹125 off on orders above ₹249",
                          discountType: "Flat",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "Flat ₹125 off on orders above ₹249 | Use code FLAT125",
                          discountType: "Flat",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "₹125 OFF",
                      shortDescriptionList: [
                        {
                          meta: "Use FLAT125",
                          discountType: "Flat",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "Flat ₹125 off on orders above ₹249 | Use code FLAT125",
                          discountType: "Flat",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    ribbon: [
                      {
                        type: "PROMOTED",
                      },
                    ],
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID:
                      "cid=5782556~p=16~eid=00000185-f8a4-4da5-1cab-9a8800c11041",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "2 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "410683",
                      deliveryTime: 26,
                      minDeliveryTime: 26,
                      maxDeliveryTime: 26,
                      lastMileTravel: 2.0999999046325684,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: true,
                    avgRating: "4.3",
                    totalRatings: 1000,
                    new: false,
                  },
                  subtype: "basic",
                },
                {
                  type: "restaurant",
                  data: {
                    type: "F",
                    id: "94703",
                    name: "Sri Punjabi Dhaba",
                    uuid: "244943ac-cb6b-439f-9a09-687af66615b1",
                    city: "1",
                    area: "BTM Layout",
                    totalRatingsString: "500+ ratings",
                    cloudinaryImageId: "i53hrycmcn2oehrojag0",
                    cuisines: ["North Indian", "Biryani", "Chinese", "Kebabs"],
                    tags: [],
                    costForTwo: 30000,
                    costForTwoString: "₹300 FOR TWO",
                    deliveryTime: 28,
                    minDeliveryTime: 28,
                    maxDeliveryTime: 28,
                    slaString: "28 MINS",
                    lastMileTravel: 2.5,
                    slugs: {
                      restaurant: "sri-punjabi-dhaba-bangalore-btm",
                      city: "bangalore",
                    },
                    cityState: "1",
                    address:
                      "Opposite 11th Cross 20th Main Rd,beside sri balaji wood Old Madiwala, Cashier Layout,  1st Stage, BTM 1st Stage, Bengaluru, Karnataka 560029",
                    locality: "Cashier Layout",
                    parentId: 21426,
                    unserviceable: false,
                    veg: false,
                    select: false,
                    favorite: false,
                    tradeCampaignHeaders: [],
                    aggregatedDiscountInfo: {
                      header: "60% off",
                      shortDescriptionList: [
                        {
                          meta: "60% off on all orders",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "60% off on all orders",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    aggregatedDiscountInfoV2: {
                      header: "60% OFF",
                      shortDescriptionList: [
                        {
                          meta: "",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      descriptionList: [
                        {
                          meta: "60% off on all orders",
                          discountType: "Percentage",
                          operationType: "RESTAURANT",
                        },
                      ],
                      subHeader: "",
                      headerType: 0,
                      superFreedel: "",
                    },
                    chain: [],
                    feeDetails: {
                      fees: [
                        {
                          name: "distance",
                          fee: 3300,
                          message: "",
                        },
                        {
                          name: "time",
                          fee: 0,
                          message: "",
                        },
                        {
                          name: "special",
                          fee: 0,
                          message: "",
                        },
                      ],
                      totalFees: 3300,
                      message: "",
                      title: "Delivery Charge",
                      amount: "3300",
                      icon: "",
                    },
                    availability: {
                      opened: true,
                      nextOpenMessage: "",
                      nextCloseMessage: "",
                    },
                    longDistanceEnabled: 0,
                    rainMode: "NONE",
                    thirdPartyAddress: false,
                    thirdPartyVendor: "",
                    adTrackingID: "",
                    badges: {
                      imageBased: [],
                      textBased: [],
                      textExtendedBadges: [],
                    },
                    lastMileTravelString: "2.5 kms",
                    hasSurge: false,
                    sla: {
                      restaurantId: "94703",
                      deliveryTime: 28,
                      minDeliveryTime: 28,
                      maxDeliveryTime: 28,
                      lastMileTravel: 2.5,
                      lastMileDistance: 0,
                      serviceability: "SERVICEABLE",
                      rainMode: "NONE",
                      longDistance: "NOT_LONG_DISTANCE",
                      preferentialService: false,
                      iconType: "EMPTY",
                    },
                    promoted: false,
                    avgRating: "3.0",
                    totalRatings: 500,
                    new: false,
                  },
                  subtype: "basic",
                },
              ],
              totalRestaurants: 1858,
            },
            subtype: "personalized",
          },
          parentWidget: false,
        },
      ],
      nextPageFetch: 0,
    },
    tid: "72a27ead-d7e5-4644-bb4c-cbdbb1992f89",
    sid: "534a8eb9-170d-4503-b69c-1baa326bc799",
    deviceId: "7cccae53-7678-e165-1a13-34e3685906d3",
    csrfToken: "ZNw0JC3NS8ei-AHYijofgRdqyM3yi-d1L5tYYM7w",
  },
];


export const AboutSectionData = [{
  "id": "01",
  "title" : "About",
  "description" : "loren ipsum text ",
  "isVisible" : true,
},{
  "id": "02",
  "title" : "Team",
  "description" : "loren ipsum text ",
  "isVisible" : true,
},{
  "id": "03",
"title" : "Careers ",
  "description" : "loren ipsum text ", 
  "isVisible" : false,
}
];
  
export const initialThemeState = {
  darkMode : false
};

export default restaurantListConfig;
